
image:
  file: .gitpod.Dockerfile

tasks:    
  - name: Postinstall .NET 6.0 and dev certificates
    init: |
      dotnet dev-certs https 
      dotnet restore

vscode:
  extensions:
    - muhammad-sammy.csharp